name: CI/CD for Java Project

on:
  push:
    branches: [main, zlatkinaea]
  pull_request:
    branches: [main, zlatkinaea]
  schedule:
    - cron: '30 12 * * 3'
    - cron: '0 22 * * 5'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        java: [11, 13, 17]
    steps:
      - uses: actions/checkout@v4
      
      - uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.java }}
          distribution: temurin
      
      - run: chmod +x gradlew
        if: runner.os != 'Windows'
      
      - run: ./gradlew build
